### ISSUE TITLE
Multiple chips

### ISSUE THREAD

**Issue by albertor24** [mohbasheer/angular-chips#17]
If the same window is using multiple <chips>, there's no way to know which array is being modified, which makes validation harder.

Moreover, we cannot pass extra parameters to the function inside render because getParamKey won't recognise data if there are commas inside the function.

A workaround I am using is 

```
var commaIndex = funStr.indexOf(',');
rightSubstr = commaIndex !==-1 ? commaIndex : closeParenthesisIndex;
return funStr.substr(openParenthesisIndex, rightSubstr - openParenthesisIndex);
```

**Comment by mohbasheer** [comment]
Hi,

Sorry for the delayed response. 

Question From You:
If the same window is using multiple , there's no way to know which array is being modified, which makes validation harder.

Question from me:
You mean to say that, When you use multiple chips in same page, you are unable to detect which array being updated?  as per my knowledge it won't happen. because it will update the model which you pass. Could you please create code-pen example for the same it will be easy to fix.

Question from you:
we cannot pass extra parameters to the function inside render.

Answer :
Yes we can't. I have given explanation here #22 please check.
