### ISSUE TITLE
Pass additional parameters to render callback.

### ISSUE THREAD

**Issue by vinay-naik** [mohbasheer/angular-chips#22]
Hi, 
Right now if i pass more than one parameter in render function i get data as undefined.

render="customValidation(data, customIndex, customIndex2)"

In the function customValidation i get data as undefined. It works fine with just one parameter data.

**Comment by mohbasheer** [comment]
Hi Vinay,

Thanks for checking with me.

Passing more then one param may not be more useful. because `<chips` is an `isolate scope` directive. it can't access it's parent scope. ok. please check the below example for clear understanding.

Let's say my controller is `customRenderingController` and it has below values.

`function CustomRendering() {
  this.countries = [{ name: 'India', fl: 'I' }, { name: 'China', fl: 'C' }, { name: 'America', fl: 'A' }];
    this.myAge = 25;
}`

my intension is passing `myAge` to `render` method like below

`<div ng-controller="customRenderingController as custom">
        <chips ng-model="custom.countries" render="custom.render(data,custom.myAge)">`

But it won't work because `<chips` directive will read it as `'custom.myAge'` only not as `25`. Because it's an isolate scope directive. 

But we can make it work for passing static data like below

`<div ng-controller="customRenderingController as custom">
        <chips ng-model="custom.countries" render="custom.render(data,25, 'red color')">`

But instead of passing static values from template. we can directly add static values in our controller render method in this case `custom.render`. What you think ?

Please let me know If I'm not clear or If I miss anything.

Thanks.
